project:
  type: website
  output-dir: docs
website:
  title: "Analyse"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Statistics
      - href: Graphs.qmd
        text: Graphs
      - href: econometrics.qmd
        text: Econometrics

format:
  html:
    theme: flaply
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Show Code"
    self_contained: false