project:
  type: website
  output-dir: docs
website:
  title: "Project"
  navbar:
    left:
      - href: /index.html
        text: Home
      - href: /about.html
        text: Statistics
      - href: /graphs.html
        text: Graphs

format:
  html:
    theme: flaply
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Show Code"