### Matrice de corrélation
<div class="graph-section">
  <h2>Corrélation </h2>
  <p>Compétences les plus associées à l'innovation (au nombre de brevets)</p>
```{r,echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(dplyr)
library(patchwork)
library(wordcloud2)
library(scales)
library(corrplot)
library(knitr)    
library(kableExtra)   
library(ggplot2)    
library(tidyr)        
library(forcats)
library(ggforce)
library(stringr)
library(corrplot)
library(readr)
library(dplyr)
library(kableExtra)
base_emp_inno <- read_delim(
  "data/base_emp_inno.csv",  # Path to the CSV file
  delim = ";",              # Delimiter used in the CSV file
  col_names = TRUE,         # Use the first row as column names
  col_types = cols(
    .default = "c",         # Treat all columns as character by default
    n_patents = "n",        # Parse 'n_patents' as numeric
    n_offres = "n",         # Parse 'n_offres' as numeric
    avg_wage = "n"          # Parse 'avg_wage' as numeric
  ),
  trim_ws = TRUE            # Trim whitespace from character strings
)
base_emp_inno <- base_emp_inno |>
  mutate(
    avg_wage = as.numeric(avg_wage),
    n_offres = as.numeric(n_offres),
    avg_req_exp = as.numeric(avg_req_exp),
    n_patents = as.numeric(n_patents)
  )

data_numeric <- base_emp_inno[, c("avg_wage", "n_offres", "avg_req_exp", "n_patents")]
matrice_correlation <- round(cor(data_numeric, use = "complete.obs"), 2)
corrplot(matrice_correlation,
method = "color",
type = "upper",
tl.col = "black",
diag = FALSE,
number.cex = 1.5,
tl.cex = 1.2,
number.digits = 2,
col = colorRampPalette(c("blue", "grey97", "red"))(200),
addCoef.col = "white",
font.lab = 2)

```
La matrice de corrélation révèle une relation positive modérée (0.31) entre le salaire moyen (**avg_wage**) et l'expérience moyenne requise (**avg_req_exp**), indiquant que des salaires plus élevés sont généralement associés à des postes nécessitant davantage d'expérience. En revanche, une corrélation négative plus faible (-0.28) est observée entre le salaire moyen et le nombre de brevets déposés (**n_patents**), suggérant que les entreprises avec un grand nombre de brevets offrent en moyenne des salaires légèrement inférieurs. Enfin, les relations impliquant le nombre d'offres d'emploi (**n_offres**) sont très faibles, ce qui montre une quasi-indépendance entre cette variable et les autres. 
Globalement, seule la relation entre salaire moyen et expérience requise ressort clairement, tandis que les autres variables présentent des corrélations négligeables.

</div>






<div class="graph-section">
  <h2>Caractères </h2>
  <p>Compétences les plus associées à l'innovation (au nombre de brevets)</p>

<table style="text-align:center"><caption><strong>Résultats</strong></caption>
<tr><td colspan="3" style="border-bottom: 1px solid black"></td></tr><tr><td style="text-align:left"></td><td colspan="2"><em>Dependent variable:</em></td></tr>
<tr><td></td><td colspan="2" style="border-bottom: 1px solid black"></td></tr>
<tr><td style="text-align:left"></td><td colspan="2">log_n_patents</td></tr>
<tr><td style="text-align:left"></td><td>(1)</td><td>(2)</td></tr>
<tr><td colspan="3" style="border-bottom: 1px solid black"></td></tr><tr><td style="text-align:left">log_avg_wage</td><td>-0.462<sup>**</sup></td><td>-0.863<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.206)</td><td>(0.299)</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td></tr>
<tr><td style="text-align:left">log_n_offres</td><td></td><td>0.040</td></tr>
<tr><td style="text-align:left"></td><td></td><td>(0.099)</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td></tr>
<tr><td style="text-align:left">avg_req_exp</td><td></td><td>-0.028</td></tr>
<tr><td style="text-align:left"></td><td></td><td>(0.039)</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td></tr>
<tr><td style="text-align:left">Constant</td><td>5.087<sup>**</sup></td><td>9.377<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td>(2.194)</td><td>(3.155)</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td></tr>
<tr><td colspan="3" style="border-bottom: 1px solid black"></td></tr><tr><td style="text-align:left">Observations</td><td>162</td><td>87</td></tr>
<tr><td style="text-align:left">R<sup>2</sup></td><td>0.031</td><td>0.117</td></tr>
<tr><td style="text-align:left">Adjusted R<sup>2</sup></td><td>0.024</td><td>0.085</td></tr>
<tr><td style="text-align:left">Residual Std. Error</td><td>1.008 (df = 160)</td><td>0.853 (df = 83)</td></tr>
<tr><td style="text-align:left">F Statistic</td><td>5.034<sup>**</sup> (df = 1; 160)</td><td>3.658<sup>**</sup> (df = 3; 83)</td></tr>
<tr><td colspan="3" style="border-bottom: 1px solid black"></td></tr><tr><td style="text-align:left"><em>Note:</em></td><td colspan="2" style="text-align:right"><sup>*</sup>p<0.1; <sup>**</sup>p<0.05; <sup>***</sup>p<0.01</td></tr>
</table>

</div>